apiVersion: v2
name: crd_dependency
description: A Helm chart for Kubernetes

type: application

version: 3.3.3
appVersion: v1.13.1

maintainers:
  - name: G
    url: https://gumeniuc.me

kubeVersion: ">=1.30.0-0"

dependencies:
  - name: crds
    version: 3.3.3
    repository: ""
    condition: crds.install
